service: link-checker-bot

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    BOT_TOKEN: <telegram bot token>
    NODE_ENV: production
    MONGODB_URI: <mongo uri>
    OWNER_CHAT_ADDRESS: <owner chat address>
    CHECK_LINK_TIMEOUT: 10000

functions:
  linkCheckerBot:
    handler: bot.handler.linkCheckerBot
    memorySize: 128
    timeout: 3
    events:
      - http:
          path: link-checker-bot
          method: post
          cors: true

  # cron:
  #   handler: cron.cron
  #   events:
  #     - schedule: cron(0 8 ? * MON *)

  schedule:
    handler: link-checker.schedule.schedule
    memorySize: 128
    timeout: 3
    events:
      - schedule: cron(0 8 ? * MON *)

  checkScheduledLink:
    handler: link-checker.checkScheduledLink.checkScheduledLink
    memorySize: 256
    timeout: 10
    reservedConcurrency: 2
    events:
      - sqs: arn:aws:sqs:eu-west-1<sqs address>:LinkCheckerBotQueue

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "LinkCheckerBotQueue"

