service: link-checker-bot

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  environment:
    BOT_TOKEN: 2093000892:AAEGZd26QueCsUcjtsIJ6tTcxPoU8hlHd1w
    NODE_ENV: production
    URL: https://syprx7m2hl.execute-api.eu-west-1.amazonaws.com/dev/link-checker-bot

functions:
  linkCheckerBot:
    handler: handler.linkCheckerBot
    events:
      - http:
          path: link-checker-bot
          method: post
          cors: true
